comment:
  layout: "header, files, footer" # remove "new" from "header" and "footer"
  hide_project_coverage: false # set to false
  require_changes: false  # if true: only post the comment if coverage changes

codecov:
  #due to ci-optimization, reports for modules that have not changed may be quite old
  max_report_age: off

coverage:
  status:
    project:
      default:
        target: 0% # no threshold enforcement yet
        only_pulls: true
    patch:
      default:
        target: 90% # for new code added in the patch
        only_pulls: true
